services:
  server:
    build: backend/
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
  client_web:
    build: web/
    depends_on:
      - server
    ports:
      - "8081:8081"
    volumes:
      - ./web/src:/app/src
